spring:
  cloud:
    openfeign:
      client:
        config:
          users:
            url: ${compare.products.api}
  data:
   redis:
     host: ${REDIS_HOST}
     port: ${REDIS_PORT}
     username: ${REDIS_USERNAME}
     password: ${REDIS_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
eureka:
  client:
   service-url:
    defaultZone: ${DISCOVERY_URI} 
server:
  port: 8080
