spring:
  application:
    name: servicio-productos-info-comercial
  threads:
    virtual:
      enabled: true
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
   host: ${RABBITMQ_HOST:localhost}
   port: ${RABBITMQ_PORT:5672}
   username: ${RABBITMQ_USERNAME:guest}
   password: ${RABBITMQ_PASSWORD:guest}
server:
  port: 9091
 
management:
  security:
    enabled: false   
  endpoints:
    web:
      exposure:
        include: "*"
        